import * as jspb from 'google-protobuf'



export enum ChatType { 
  CHATTYPE_UNKNOWN = 0,
  CHATTYPE_PRIVATE = 1,
}
export enum UserType { 
  USERTYPE_UNKNOWN = 0,
  USERTYPE_GUEST = 1,
  USERTYPE_GOOGLE = 2,
  USERTYPE_TWITTER = 3,
  USERTYPE_FACEBOOK = 4,
  USERTYPE_PASSWORD = 5,
}
export enum UserAccess { 
  USERACCESS_UNKNOWN = 0,
  USERACCESS_PUBLIC = 1,
  USERACCESS_PRIVATE = 2,
}
export enum UserStatus { 
  USERSTATUS_UNKNOWN = 0,
  USERSTATUS_CONNECTED = 1,
  USERSTATUS_DISCONNECTED = 2,
}
export enum UserOption { 
  USEROPTION_UNKNOWN = 0,
  USEROPTION_IGNORE_MESSAGES = 1,
  USEROPTION_DISPLAY_FULLNAME = 2,
}
export enum UserRelationType { 
  USERRELATIONTYPE_UNKNOWN = 0,
  USERRELATIONTYPE_BLOCK = 1,
  USERRELATIONTYPE_FRIEND = 2,
  USERRELATIONTYPE_INVITE = 3,
  USERRELATIONTYPE_FOLLOW = 4,
}
